version: '2'

services:
  itau-api-db:
    build:
        context: .
        dockerfile: Dockerfile 
    image: itau-api-db:1.0
    container_name: itau-api-db
    hostname: itau-api-db-docker
    ports:
    - "9000:9000"
    - "9010:9010"
    networks:
    - itau-api-network   
networks:
  itau-api-network:
    driver: bridge